apiVersion: v1
kind: PersistentVolume
metadata:
  name: avm-server-1-pv-volume
  labels:
    type: local
    app: avm-server-01
    avm-server-num: avms-01
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: 'C:\AVMContainerizeLog\VMSLog1'
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: beta.kubernetes.io/os
          operator: In
          values:
          - windows

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: avm-server-1-pv-claim
  labels:
    app: avm-server-01
    avm-server-num: avms-01
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: avm-model-1-pv-volume
  labels:
    type: local
    app: avm-server-01
    avm-server-num: avms-01
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: 'C:\vms1\UpdateModel'
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: beta.kubernetes.io/os
          operator: In
          values:
          - windows

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: avm-model-1-pv-claim
  labels:
    app: avm-server-01
    avm-server-num: avms-01
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi