apiVersion: v1
kind: Service
metadata:
  name: system-monitor-service
  labels:
    app: system-monitor
spec:
  clusterIP: "10.100.0.4"
  selector:
    app: system-monitor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30800
  type: NodePort
