apiVersion: v1
kind: ServiceAccount
metadata:
  name: apiserver
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: apiserver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: apiserver
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: apiserver
  labels:
    app: webserver
spec:
  serviceAccountName: apiserver
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: apiserver
    image: imrc/apiserver
    ports:
    - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30390
    protocol: TCP
    targetPort: 8080
  selector:
    app: webserver