apiVersion: v1
kind: Service
metadata:
  name: amc-service
  labels:
    app: amc
spec:
  clusterIP: "10.100.0.7"
  selector:
    app: amc
  ports:
    - protocol: TCP
      port: 8765
      targetPort: 8765
      nodePort: 30765
  type: NodePort
