apiVersion: v1
kind: Service
metadata:
  name: vmm-service
  labels:
    app: vmm
spec:
  clusterIP: "10.100.0.6"
  selector:
    app: vmm
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087
      nodePort: 30087
  type: NodePort
