apiVersion: v1
kind: PersistentVolume
metadata:
  name: vmm-pv-volume
  labels:
    type: local
    app: vmm
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: 'C:\AVMContainerizeLog\VMMLog'
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: beta.kubernetes.io/os
          operator: In
          values:
          - windows

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vmm-pv-claim
  labels:
    app: vmm
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi