apiVersion: v1
kind: Service
metadata:
  name: sic-agent-service
  labels:
    app: sic-agent
spec:
  clusterIP: "10.100.0.5"
  selector:
    app: sic-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30801
  type: NodePort
